# Generated by Django 3.2.12 on 2022-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='new_field',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
